---
title: "HCD Simulations Write Up"
author: "Audrey Fu Lab"
date: "2024-03-07"
output:
 pdf_document:
   keep_tex: true
   number_sections: true
always_allow_html: true
header-includes:
  - \usepackage{float}
  - \usepackage{multirow}
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  # - \pagenumbering{gobble}
  - \pagestyle{fancy}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=10, fig.pos = "H")
#knitr::opts_chunk$set(list(echo = FALSE, eval = FALSE))
library(kableExtra)
library(knitr)
library(latex2exp)
library(gridExtra)
library(ggpubr)
library(ggthemes)
library(plyr)
basepath = 'C:/Users/Bruin/Documents/GitHub/HGRN_repo/Simulated Hierarchies/'

library(ggpubr)
tab = read.csv(paste0(basepath, 'DATA/Toy_examples/Intermediate_examples/Results/MASTER_results.csv'))




```


\section*{Simulation Description}


\section*{Preliminary Findings}



\newpage
\section*{Figures}
```{r, echo=F, message=F, warning=F, fig.height=8, fig.width=10}

longform = cbind.data.frame(metric = as.factor(c(rep('homogeneity', dim(tab)[1]),
                              rep('completeness', dim(tab)[1]),
                              rep('NMI', dim(tab)[1]))),
                            lambda_top = as.factor(rep(tab$Lambda_top, 3)),
                            lambda_middle = as.factor(rep(tab$Lambda_middle, 3)),
                            network = as.factor(rep(tab$Network_type, 3)),
                            input_graph = as.factor(rep(tab$input_graph, 3)),
                            gamma = as.factor(rep(tab$Gamma, 3)),
                            TOAL_loss = as.factor(rep(tab$TOAL_Loss, 3)),
                            resolution_top = as.factor(rep(tab$Resolution_top, 3)),
                            resolution_middle = as.factor(rep(tab$Resolution_middle, 3)),
                            Top.stats = c(tab$Top_homogeneity, tab$Top_completeness, tab$Top_NMI),
                            Mid.stats = c(tab$Middle_homogeneity, tab$Middle_Completeness, tab$Middle_NMI),
                            Louvain.top = c(tab$Louvain_homogenity_top, 
                                            tab$Louvain_completeness_top, 
                                            tab$Louvain_NMI_top),
                            Louvain.middle = c(tab$Louvain_homogenity_middle, 
                                               tab$Louvain_completeness_middle,
                                               tab$Louvain_NMI_middle))




longform.x = cbind.data.frame(method = c(rep(rep('HCD', dim(tab)[1]),3),
                                         rep(rep('Louvain', dim(tab)[1]),3)),
                              metric = as.factor(c(rep('homogeneity', dim(tab)[1]),
                                                   rep('completeness', dim(tab)[1]),
                                                   rep('NMI', dim(tab)[1]))),
                              TOAL = as.factor(rep(rep(tab$TOAL_Loss, 3),2)),
                              network = as.factor(rep(rep(tab$Network_type, 3),2)),
                              input_graph = as.factor(rep(rep(tab$input_graph, 3),2)),
                              performance.top = c(c(tab$Top_homogeneity, 
                                                    tab$Top_completeness, 
                                                    tab$Top_NMI),
                                                  c(tab$Louvain_homogenity_top, 
                                                    tab$Louvain_completeness_top, 
                                                    tab$Louvain_NMI_top)),
                              performance.middle = c(c(tab$Middle_homogeneity, 
                                                       tab$Middle_Completeness, 
                                                       tab$Middle_NMI),
                                                     c(tab$Louvain_homogenity_middle, 
                                                       tab$Louvain_completeness_middle,
                                                       tab$Louvain_NMI_middle)))



# comparing HCD with louvain on graph type 
A = ggplot(data = longform.x, aes(x = method, y = performance.top, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~network)+
  theme_classic2()+
  theme(legend.position = 'top')

B = ggplot(data = longform.x, aes(x = method, y = performance.middle, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~network)+
  theme_classic2()+
  theme(legend.position = 'top')


ggarrange(A, B, nrow = 2, common.legend = T)
```



```{r, echo=F, message=F, warning=F, fig.height=8, fig.width=10}


# comparing HCD with louvain on input graph 
A = ggplot(data = longform.x, aes(x = method, y = performance.top, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top')

B = ggplot(data = longform.x, aes(x = method, y = performance.middle, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top')


ggarrange(A, B, nrow = 1, common.legend = T)

```




```{r, echo=F, message=F, warning=F, fig.height=8, fig.width=10, fig.cap='Small world graphs'}
longform2 = cbind.data.frame(method = as.factor(c(rep('HCD', dim(longform)[1]), 
                                        rep('Louvain', dim(longform)[1]))),
                             metric = as.factor(rep(c(rep('homogeneity', dim(tab)[1]),
                                         rep('completeness', dim(tab)[1]),
                                         rep('NMI', dim(tab)[1])), 2)),
                  network = as.factor(rep(tab$Network_type, 6)),
                  input_graph = as.factor(rep(tab$input_graph, 6)),
                  gamma = as.factor(rep(tab$Gamma, 6)),
                  resolution_top = as.factor(rep(tab$Resolution_top, 6)),
                  resolution_middle = as.factor(rep(tab$Resolution_middle, 6)),
                  stats.top = c(longform$Top.stats, longform$Louvain.top),
                  stats.mid = c(longform$Mid.stats, longform$Louvain.top))
                  
                  
                  
                  
#Top level comparison
#smallworld network
lf1.1 = subset(longform2, network == 'small world')
A =ggplot(data = lf1.1, aes(x = method, y = stats.top, 
                             fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Top Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))


B =ggplot(data = lf1.1, aes(x = method, y = stats.mid, 
                         fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Middle Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))

ggarrange(A, B, nrow = 1, common.legend = T)

```


```{r, echo=F, message=F, warning=F, fig.height=8, fig.width=10, fig.cap='Scale free graphs'}
#scale free
lf1.2 = subset(longform2, network == 'scale free')
A = ggplot(data = lf1.2, aes(x = method, y = stats.top, 
                             fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Top Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))

B = ggplot(data = lf1.2, aes(x = method, y = stats.mid, 
                         fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Middle Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))

ggarrange(A, B, nrow = 1, common.legend = T)
```


```{r, echo=F, message=F, warning=F, fig.height=8, fig.width=10, fig.cap='random graphs'}
#random graph
lf1.3 = subset(longform2, network == 'random graph')
A = ggplot(data = lf1.3, aes(x = method, y = stats.top, 
                             fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Top Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))

B = ggplot(data = lf1.3, aes(x = method, y = stats.mid, 
                         fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Middle Layer Performance')+
  facet_wrap(~input_graph)+
  theme_classic2()+
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))

ggarrange(A, B, nrow = 1, common.legend = T)
```








\newpage 
\section*{Tables}

```{r, echo=F, message=F, warning=F}

net_stats = read.csv('C:/Users/Bruin/Documents/GitHub/HGRN_repo/Simulated Hierarchies/DATA/Toy_examples/Intermediate_examples/intermediate_examples_network_statistics.csv')[,-1]

net_stats$modularity_top = round(net_stats$modularity_top, 3)
net_stats$avg_node_degree_top = round(net_stats$avg_node_degree_top, 3)
net_stats$avg_connect_within_top = round(net_stats$avg_connect_within_top, 3)
net_stats$avg_connect_between_top = round(net_stats$avg_connect_between_top, 3)
net_stats$modularity_middle = round(net_stats$modularity_middle, 3)
net_stats$avg_node_degree_middle = round(net_stats$avg_node_degree_middle, 3)
net_stats$avg_connect_within_middle = round(net_stats$avg_connect_within_middle, 3)
net_stats$avg_connect_between_middle = round(net_stats$avg_connect_between_middle, 3)

df = rbind.data.frame(c('Subgraph type','Connection type','Layers','Standard deviation','Nodes per layer','Edges per layer','Subgraph probability','Sample size', 'Modularity (top)', 'Average node degree top', 'Avg connections within top communities','Avg. connections between top communities', 'Modularity (middle)', 'Average node degree middle', 'Avg connections within middle communities', 'Avg connections between middle communities'), net_stats)

kable(t(df), format = 'latex', digits = 2, row.names = F, col.names = c('Value', paste0('Network', c(1:6))),
                                                                                    booktabs = T,
      caption = 'Summary statistics for intermediate difficulty simulated networks.')%>%kable_styling(latex_options = c("striped", "hold_postion"),font_size = 10)%>%kable_styling(font_size = 10)%>%column_spec(1, '8em')
```

\clearpage
\newpage
```{r, echo=F, message=F, warning=F}

grid = expand.grid(`Input Graph` = unique(tab$input_graph),
                   `Graph Recon. Loss` = c('1 = on', '0 = off'),
                   `Attr. Recon. Loss` = c('False (on)', 'True (off)'),
                   `Modularity Weigth` = c('1 = on', '0 = off'),
                   `Clust. Weight` = c('1 (middle), 1 (top)', '0.1 (middle), 1e-4 (top)'))

df = cbind.data.frame(`Scenario` = c(1:dim(grid)[1]), grid)
kable(df, format = 'markdown', digits = 2, row.names = F, booktabs = T,
      caption = 'Simulation settings for intermediate difficulty networks. Each row represents a single simulation scenario applied to all 6 simulated networks given in Table 1')
```
