---
title: "Lab report: HCD progress update"
author: "Jarred Kvamme - Audrey Fu Lab"
date: "2024-01-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(latex2exp)


tab = read.csv('C:/Users/Bruin/Documents/GitHub/HGRN_repo/Simulated Hierarchies/Results_Tables_and_Figures/MASTER_results.csv')
tab$input_graph[tab$input_graph == 'A_ingraph_true'] = 'Input graph: True graph'
tab$input_graph[tab$input_graph == 'A_corr_no_cutoff'] = 'Input graph: Corr. matrix'
tab$input_graph[tab$input_graph == 'A_ingraph02'] = 'Input graph: r > 0.2'
tab$input_graph[tab$input_graph == 'A_ingraph05'] = 'Input graph: r > 0.5'
tab$input_graph[tab$input_graph == 'A_ingraph07'] = 'Input graph: r > 0.7'
tab$Connection_prob[tab$Connection_prob == 'disc'] = 'Disconnected Top Layer'
tab$Connection_prob[tab$Connection_prob == 'full'] = 'Fully Connected Top Layer'
tab$Layers[tab$Layers == 2] = '2 Layers'
tab$Layers[tab$Layers == 3] = '3 Layers'
```










```{r, echo=F, message=F, warning=F, fig.height=6, fig.width=10, fig.cap=""}

longform = cbind.data.frame(metric = as.factor(c(rep('homogeneity', dim(tab)[1]),
                              rep('completeness', dim(tab)[1]),
                              rep('NMI', dim(tab)[1]))),
                            connect = as.factor(rep(tab$Connection_prob, 3)),
                            layers = rep(tab$Layers, 3),
                            network = as.factor(rep(tab$Network_type, 3)),
                            input_graph = as.factor(rep(tab$input_graph, 3)),
                            gamma = as.factor(rep(tab$Gamma, 3)),
                            resolution_top = as.factor(rep(tab$Resolution_top, 3)),
                            resolution_middle = as.factor(rep(tab$Resolution_middle, 3)),
                            Top.stats = c(tab$Top_homogeneity, tab$Top_completeness, tab$Top_NMI),
                            Mid.stats = c(tab$Middle_homogeneity, tab$Middle_Completeness,tab$Middle_NMI))


longform.louv = cbind.data.frame(metric = as.factor(c(rep('homogeneity', dim(tab)[1]),
                                                      rep('completeness', dim(tab)[1]),
                                                      rep('NMI', dim(tab)[1]))),
                                 connect = as.factor(rep(tab$Connection_prob, 3)),
                                 layers = rep(tab$Layers, 3),
                                 network = as.factor(rep(tab$Network_type, 3)),
                                 input_graph = as.factor(rep(tab$input_graph, 3)),
                                 gamma = as.factor(rep(tab$Gamma, 3)),
                                 resolution_top = as.factor(rep(tab$Resolution_top, 3)),
                                 resolution_middle = as.factor(rep(tab$Resolution_middle, 3)),
                                 Top.stats = c(tab$Louvain_homogenity_top, 
                                                 tab$Louvain_completeness_top, 
                                                 tab$Louvain_NMI_top),
                                 Mid.stats = c(tab$Louvain_homogenity_middle, 
                                                    tab$Louvain_completeness_middle,
                                                    tab$Louvain_NMI_middle))


lf.final = cbind.data.frame(Method = c(rep('HCD', dim(tab)[1]*3), 
                                              rep('Louvain', dim(tab)[1]*3)), 
                                   rbind.data.frame(longform, longform.louv))


#across connectivity
A = ggplot(data = lf.final, aes(x = Method, y = Top.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~connect)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))

B = ggplot(data = lf.final, aes(x = Method, y = Mid.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~connect)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))

ggarrange(A, B, common.legend = T, nrow = 2)
```


```{r, echo=F, message=F, warning=F, fig.height=6, fig.width=10, fig.cap=""}
#Across number of layers
A = ggplot(data = lf.final, aes(x = Method, y = Top.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~layers)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))

B = ggplot(data = subset(lf.final, layers == '3 Layers'), 
           aes(x = Method, y = Mid.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~layers)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))



ggarrange(A, B, common.legend = T, nrow = 2)


```



```{r, echo=F, message=F, warning=F, fig.height=6, fig.width=10, fig.cap=""}
#Across Types of networks
A = ggplot(data = lf.final, aes(x = Method, y = Top.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~network)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))

B = ggplot(data = lf.final, 
           aes(x = Method, y = Mid.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~network)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))


ggarrange(A, B, common.legend = T, nrow = 2)

```



```{r, echo=F, message=F, warning=F, fig.height=7, fig.width=10, fig.cap=""}

#Across input graph
A = ggplot(data = lf.final, aes(x = Method, y = Top.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Top Layer')+
  facet_wrap(~input_graph,nrow = 3)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))

B = ggplot(data = lf.final, 
           aes(x = Method, y = Mid.stats, fill = metric))+
  geom_boxplot()+
  xlab('Method')+
  ylab('Performance Middle Layer')+
  facet_wrap(~input_graph, nrow = 3)+
  theme_hc()+
  theme(legend.position = 'top', 
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 16),
        legend.text = element_text(size = 16))


ggarrange(A, B, common.legend = T, ncol = 2)




```